M48
; DRILL file {KiCad 9.0.1} date 2025-04-13T07:36:42-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-13T07:36:42-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.8661Y-3.7709
X6.0937Y-3.7709
T2
X5.12Y-2.72
X7.32Y-3.14
M30
