M48
; DRILL file {KiCad 9.0.1} date 2025-05-18T13:56:23-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-18T13:56:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X149.0Y-95.78
X154.78Y-95.78
T2
X130.048Y-69.088
X185.928Y-79.756
M30
